version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devops-blacklist"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-east-1"
    ACCOUNT_ID: "194356484319"
    URI: "194356484319.dkr.ecr.us-east-1.amazonaws.com194356484319.dkr.ecr.us-east-1.amazonaws.com"
    #ecsTaskExecutionRole

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias para pruebas..."
      - pip install -r requirements.txt
      - pip install pytest pytest-cov
      - echo "Iniciando sesión en ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  pre_build:
    commands:
      - rm -f Dockerrun.aws.json || true
      - echo "Agregando el directorio actual al PYTHONPATH..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - echo "Ejecutando pruebas unitarias..."
      - pytest tests/test_unit.py --maxfail=1 --disable-warnings -q

  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - Dockerfile
    - Dockerrun.aws.json
    - main.py
    - application.py
    - config.py
    - extensions.py
    - requirements.txt
    - generate_token.py
    - setup_db.sql
    - models/**/*
    - resources/**/*
    - .ebextensions/**/*