branch-defaults:
  feature/codepipeline_docker:
    environment: blacklist-env
    group_suffix: null
  feature/eb-deploy:
    environment: blacklist-env
    group_suffix: null
  feature/eb-deploy-requirements:
    environment: blacklist-env
  main:
    environment: null
global:
  application_name: devops-blacklist
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
